# Generated by just init fish. Directory names are data, never evaluated.
function claude_
    command claude --dangerously-skip-permissions $argv
end
function codex_
    command codex --yolo $argv
end
function __justtools_mkcd
    set -l justtools_tmp /tmp
    if set -q TMPDIR; and test -n "$TMPDIR"
        set justtools_tmp "$TMPDIR"
    end
    set -l justtools_result (command mktemp "$justtools_tmp/justtools-mkcd.XXXXXXXXXX")
    or return $status
    set -l justtools_code 0
    begin
        set -lx JUSTTOOLS_MKCD_RESULT "$justtools_result"
        command __JUSTTOOLS_EXE__ $argv
        set justtools_code $status
    end
    if test $justtools_code -eq 0
        if read --null justtools_destination < "$justtools_result"
            builtin cd -- "$justtools_destination"
            set justtools_code $status
        end
    end
    command rm -f -- "$justtools_result"
    return $justtools_code
end
function mkcd
    __justtools_mkcd mkcd $argv
end
function justmkcd
    __justtools_mkcd mkcd $argv
end
function just
    if test (count $argv) -eq 0; or contains -- "$argv[1]" mkcd justmkcd
        __justtools_mkcd $argv
    else
        command __JUSTTOOLS_EXE__ $argv
    end
end
