# Generated by just init. Directory names are data, never evaluated.
claude_() { command claude --dangerously-skip-permissions "$@"; }
codex_() { command codex --yolo "$@"; }
__justtools_mkcd() {
    local justtools_result justtools_handoff justtools_destination justtools_code
    justtools_result=$(command mktemp "${TMPDIR:-/tmp}/justtools-mkcd.XXXXXXXXXX") || return
    justtools_handoff=$justtools_result
    if command -v cygpath >/dev/null 2>&1; then
        justtools_handoff=$(command cygpath -w -- "$justtools_result")
    fi
    if JUSTTOOLS_MKCD_RESULT="$justtools_handoff" command __JUSTTOOLS_EXE__ "$@"; then
        justtools_code=0
        if IFS= read -r -d '' justtools_destination < "$justtools_result"; then
            if command -v cygpath >/dev/null 2>&1; then
                justtools_destination=$(command cygpath -u -- "$justtools_destination")
            fi
            builtin cd -P -- "$justtools_destination" || justtools_code=$?
        fi
    else
        justtools_code=$?
    fi
    command rm -f -- "$justtools_result"
    return "$justtools_code"
}
mkcd() { __justtools_mkcd mkcd "$@"; }
justmkcd() { __justtools_mkcd mkcd "$@"; }
just() {
    case "${1-}" in
        ''|mkcd|justmkcd) __justtools_mkcd "$@" ;;
        *) command __JUSTTOOLS_EXE__ "$@" ;;
    esac
}
