# Generated by just init powershell. Directory names are data, never evaluated.
function global:claude_ {
    if ($MyInvocation.ExpectingInput) { $input | & claude --dangerously-skip-permissions @args }
    else { & claude --dangerously-skip-permissions @args }
}
function global:codex_ {
    if ($MyInvocation.ExpectingInput) { $input | & codex --yolo @args }
    else { & codex --yolo @args }
}
function global:__JustToolsMkcd {
    $resultFile = [IO.Path]::GetTempFileName()
    $previousResult = $env:JUSTTOOLS_MKCD_RESULT
    $code = 1
    try {
        $env:JUSTTOOLS_MKCD_RESULT = $resultFile
        # Native processes must start in PowerShell's current filesystem location.
        $previousDirectory = [Environment]::CurrentDirectory
        $previousErrorPreference = $ErrorActionPreference
        try {
            [Environment]::CurrentDirectory = $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath('.')
            # Windows PowerShell otherwise treats native stderr as a terminating
            # exception under Stop and loses the actual command exit code.
            $ErrorActionPreference = 'Continue'
            if ($MyInvocation.ExpectingInput) { $input | & __JUSTTOOLS_EXE__ @args }
            else { & __JUSTTOOLS_EXE__ @args }
            $code = $LASTEXITCODE
        } finally {
            $ErrorActionPreference = $previousErrorPreference
            [Environment]::CurrentDirectory = $previousDirectory
        }
        if ($code -eq 0) {
            $destination = [IO.File]::ReadAllText($resultFile, [Text.Encoding]::UTF8).TrimEnd([char]0)
            # Windows PowerShell 5.1 cannot navigate extended-length prefixes.
            if ($destination.StartsWith('\\?\UNC\')) {
                $destination = '\\' + $destination.Substring(8)
            } elseif ($destination.StartsWith('\\?\')) {
                $destination = $destination.Substring(4)
            }
            if ($destination.Length -gt 0) {
                Set-Location -LiteralPath $destination -ErrorAction Stop
            }
        }
    } catch {
        $code = 1
        Write-Error -ErrorRecord $_ -ErrorAction Continue
    } finally {
        $env:JUSTTOOLS_MKCD_RESULT = $previousResult
        [IO.File]::Delete($resultFile)
        $global:LASTEXITCODE = $code
    }
}
function global:mkcd {
    if ($MyInvocation.ExpectingInput) { $input | __JustToolsMkcd mkcd @args }
    else { __JustToolsMkcd mkcd @args }
}
function global:justmkcd {
    if ($MyInvocation.ExpectingInput) { $input | __JustToolsMkcd mkcd @args }
    else { __JustToolsMkcd mkcd @args }
}
function global:just {
    if ($args.Count -eq 0 -or $args[0] -in @('mkcd', 'justmkcd')) {
        if ($MyInvocation.ExpectingInput) { $input | __JustToolsMkcd @args }
        else { __JustToolsMkcd @args }
    } else {
        if ($MyInvocation.ExpectingInput) { $input | & __JUSTTOOLS_EXE__ @args }
        else { & __JUSTTOOLS_EXE__ @args }
    }
}
